export const ALL_PAGE_REQUEST = "ALL_PAGE_REQUEST";
export const ALL_PAGE_SUCCESS = "ALL_PAGE_SUCCESS";
export const ALL_PAGE_FAIL = "ALL_PAGE_FAIL";
export const ALL_PAGE_RESET = "ALL_PAGE_RESET";

export const NEW_PAGE_REQUEST = "NEW_PAGE_REQUEST";
export const NEW_PAGE_SUCCESS = "NEW_PAGE_SUCCESS";
export const NEW_PAGE_RESET = "NEW_PAGE_RESET";
export const NEW_PAGE_FAIL = "NEW_PAGE_FAIL";

export const GET_PAGE_REQUEST = "GET_PAGE_REQUEST";
export const GET_PAGE_SUCCESS = "GET_PAGE_SUCCESS";
export const GET_PAGE_RESET = "GET_PAGE_RESET";
export const GET_PAGE_FAIL = "GET_PAGE_FAIL";

export const UPDATE_PAGE_REQUEST = "UPDATE_PAGE_REQUEST";
export const UPDATE_PAGE_SUCCESS = "UPDATE_PAGE_SUCCESS";
export const UPDATE_PAGE_RESET = "UPDATE_PAGE_RESET";
export const UPDATE_PAGE_FAIL = "UPDATE_PAGE_FAIL";

export const RESET_PAGE_REQUEST = "RESET_PAGE_REQUEST";
export const DELETE_PAGE_REQUEST = "DELETE_PAGE_REQUEST";
export const DELETE_PAGE_SUCCESS = "DELETE_PAGE_SUCCESS";
export const DELETE_PAGE_FAIL = "DELETE_PAGE_FAIL";

export const ALL_ADTYPE_REQUEST = "ALL_ADTYPE_REQUEST";
export const ALL_ADTYPE_SUCCESS = "ALL_ADTYPE_SUCCESS";
export const ALL_ADTYPE_FAIL = "ALL_ADTYPE_FAIL";
export const ALL_ADTYPE_RESET = "ALL_ADTYPE_RESET";

export const NEW_ADTYPE_REQUEST = "NEW_ADTYPE_REQUEST";
export const NEW_ADTYPE_SUCCESS = "NEW_ADTYPE_SUCCESS";
export const NEW_ADTYPE_RESET = "NEW_ADTYPE_RESET";
export const NEW_ADTYPE_FAIL = "NEW_ADTYPE_FAIL";

export const GET_ADTYPE_REQUEST = "GET_ADTYPE_REQUEST";
export const GET_ADTYPE_SUCCESS = "GET_ADTYPE_SUCCESS";
export const GET_ADTYPE_RESET = "GET_ADTYPE_RESET";
export const GET_ADTYPE_FAIL = "GET_ADTYPE_FAIL";

export const UPDATE_ADTYPE_REQUEST = "UPDATE_ADTYPE_REQUEST";
export const UPDATE_ADTYPE_SUCCESS = "UPDATE_ADTYPE_SUCCESS";
export const UPDATE_ADTYPE_RESET = "UPDATE_ADTYPE_RESET";
export const UPDATE_ADTYPE_FAIL = "UPDATE_ADTYPE_FAIL";

export const RESET_ADTYPE_REQUEST = "RESET_ADTYPE_REQUEST";
export const DELETE_ADTYPE_REQUEST = "DELETE_ADTYPE_REQUEST";
export const DELETE_ADTYPE_SUCCESS = "DELETE_ADTYPE_SUCCESS";
export const DELETE_ADTYPE_FAIL = "DELETE_ADTYPE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
